services:
  - type: web
    name: mindsupport-api
    env: node
    buildCommand: yarn install && yarn build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: STREAM_API_KEY
        sync: false
      - key: STREAM_API_SECRET
        sync: false
      - key: PUBLISH_SECRET
        generateValue: true
      - key: REDIS_URL
        sync: false
    healthCheckPath: /health